### ISSUE TITLE
Add C++ Protobuf example

### ISSUE THREAD

**Issue by jtbandes** [foxglove/ws-protocol#138]
We should provide example code for using Protobuf encoding in C++.

This will also require importing or adding our own base64 encoding implementation.

**Comment by felixf4xu** [comment]
please~

We are using python but for some online data visualization (10Hz and 20Hz or even higher), python's performance is now a bottleneck to parse protobuf data.

**Comment by felixf4xu** [comment]
I'm using https://gist.github.com/tomykaira/f0fd86b6c73063283afe550bc5d77594 for base64 encoding
