### ISSUE TITLE
Add way to verify server setup is complete (C++)

### ISSUE THREAD

**Issue by cody-sheff** [foxglove/ws-protocol#153]
It does not appear that there is currently any way to verify whether or not a server's setup is complete; a function that allows for easily verifying this would be helpful for determining when execution can begin without risk of losing initial data.

**Comment by jtbandes** [comment]
Can you say more about what you mean by complete? Do you need information about how many clients have connected/subscribed, or what would constitute a fully set up server in your case?

**Comment by cody-sheff** [comment]
Information about how many clients have connected/subscribed would probably be sufficient. That way I could pause execution until at least one client has connected and then resume.

**Comment by jtbandes** [comment]
Would the existing `setSubscribeHandler` function work for that purpose? The function you provide will be called the first time a client subscribes to each channel.

**Comment by cody-sheff** [comment]
That worked for my purposes, thank you so much!
