### ISSUE TITLE
Can't build cpp project with docker

### ISSUE THREAD

**Issue by felixf4xu** [foxglove/ws-protocol#181]
**Description**

- Version: master branch
- Platform: WSL2, docker is installed and service is started

**Steps To Reproduce**

I'm trying to build c++ version, so in `cpp` folder:
`make build`
```sh
docker compose build
docker: 'compose' is not a docker command.
See 'docker --help'
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 1
```
**Expected Behavior**

build cpp project

ps

I have installed `pip install docker-compose`
docker-compose -version
```sh
/home/f/.local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
docker-compose version 1.29.2, build unknown
```

**Comment by jtbandes** [comment]
Try upgrading your version of Docker

**Comment by felixf4xu** [comment]
sorry, it's my docker user group permission issue, now it can be compiled.
