### ISSUE TITLE
Performance test Foxglove Websocket

### ISSUE THREAD

**Issue by amacneil** [foxglove/ws-protocol#28]
Questions came up around sending 4 channels of raw images @ 15hz, ~8mb per frame (~1 Gbps per channel).

We should create a simple performance test to generate data using the Python (and/or JS) Websocket server, generating large quantities of random data, and see how fast we can get this into Studio and where the current bottlenecks are.

**Comment by defunctzombie** [comment]
Removed @jtbandes assignment for now. Many other things with higher priority.

**Comment by jhurliman** [comment]
Performance test performed from a ROS 1 environment on an NVIDIA Jetson TX2 to Studio running in a Chrome browser on a MBP M1, both connected via Ethernet. Streaming a 720p raw image topic at 30hz, connecting to `rosbridge` gets around ~19hz while connecting to `ros-foxglove-bridge` gets a full 30hz.
