### ISSUE TITLE
Update npx @foxglove/ws-protocol-examples to use Foxglove schemas

### ISSUE THREAD

**Issue by jtbandes** [foxglove/ws-protocol#302]
At least the image-server example is still using a `ros.sensor_msgs.CompressedImage` schema. This should be changed to a `foxglove.CompressedImage`.

**Comment by jhurliman** [comment]
Possible duplicate of https://github.com/foxglove/ws-protocol/issues/162

**Comment by jtbandes** [comment]
Hah, yes
