### ISSUE TITLE
CI: C++ build fails

### ISSUE THREAD

**Issue by achim-k** [foxglove/ws-protocol#351]
**Description**

```
#15 70.52 protobuf/3.21.4: Configuring sources in /root/.conan/data/protobuf/3.21.4/_/_/source/src
#15 70.93 ERROR: protobuf/3.21.4: Error in source() method, line 86
#15 70.93 	get(self, **self.conan_data["sources"][self.version], strip_root=True)
#15 70.93 	ConanException: sha256 signature failed for 'v3.21.4.tar.gz' file. 
#15 70.93  Provided signature: 85d42d4485f36f8cec3e475a3b9e841d7d78523cd775de3a86dba77081f4ca25  
#15 70.93  Computed signature: efdaaf08f34af3b6cd906e59e181e3e30589a2fc2cc9d89036f92d529b9fe1cd
failed to solve: executor failed running [/bin/sh -c conan install examples --install-folder examples/build --build=openssl --build=zlib --build=protobuf]: exit code: 1
#15 ERROR: executor failed running [/bin/sh -c conan install examples --install-folder examples/build --build=openssl --build=zlib --build=protobuf]: exit code: 1
------
make: *** [Makefile:5: build] Error 17
 > [build_example_server 5/5] RUN conan install examples --install-folder examples/build --build=openssl --build=zlib --build=protobuf:
```

See https://github.com/foxglove/ws-protocol/actions/runs/4047568126 for more details

**Expected Behavior**
No CPP build failures

**Comment by jhurliman** [comment]
Was this a transient error? C++ build succeeded for me in several CI runs a few minutes ago.

**Comment by achim-k** [comment]
It could be. Will confirm and close this issue if it can't be reproduced

**Comment by adityasivarajmz** [comment]
I am getting the same error code while building CPP examples.
`[+] Building 63.4s (8/9)                                                                                                                    
 => [internal] load .dockerignore                                                                                                      0.2s
 => => transferring context: 156B                                                                                                      0.0s
 => [internal] load build definition from dev.Dockerfile                                                                               0.2s
 => => transferring dockerfile: 1.29kB                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:jammy                                                                        3.3s
 => [base 1/3] FROM docker.io/library/ubuntu:jammy@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f             1.3s
 => => resolve docker.io/library/ubuntu:jammy@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f                  0.0s
 => => sha256:58db3edaf2be6e80f628796355b1bdeaf8bea1692b402f48b7e7b8d1ff100b02 2.30kB / 2.30kB                                         0.0s
 => => sha256:677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8 29.53MB / 29.53MB                                       0.8s
 => => sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f 1.13kB / 1.13kB                                         0.0s
 => => sha256:c985bc3f77946b8e92c9a3648c6f31751a7dd972e06604785e47303f4ad47c4c 424B / 424B                                             0.0s
 => => extracting sha256:677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8                                              0.4s
 => [base 2/3] RUN apt-get update &&     apt-get install -y --no-install-recommends --no-install-suggests     ca-certificates     cu  53.7s
 => [base 3/3] WORKDIR /src                                                                                                            0.1s 
 => [build 1/3] RUN pip --no-cache-dir install conan                                                                                   4.1s 
 => ERROR [build 2/3] RUN conan config init                                                                                            0.6s 
------                                                                                                                                      
 > [build 2/3] RUN conan config init:                                                                                                       
#0 0.586 usage: conan config [-h] [-v [V]] [--logger] {home,install,list} ...                                                               
#0 0.586 conan config: error: argument subcommand: invalid choice: 'init' (choose from 'home', 'install', 'list')
#0 0.586 ERROR: Exiting with code: 2
------
failed to solve: process "/bin/sh -c conan config init" did not complete successfully: exit code: 2
make: *** [Makefile:5: build] Error 17

How do I solve this?`

**Comment by adityasivarajmz** [comment]
I found the problem. Conan was updated to version 2.0.0 few days ago. It doesn't have the _init_ command under `conan config`. FIX: Change line 25 in _dev.Dockerfile_ to `RUN pip --no-cache-dir install conan==1.59.0`

**Comment by achim-k** [comment]
Indeed, we are currently in the process of migrating to conan 2.x. See #375
