### ISSUE TITLE
Bandwidth is not fully utilized

### ISSUE THREAD

**Issue by wangqiim** [foxglove/ws-protocol#508]
**Description**
The data source and foxlove frontend run on different hosts machine, and when I use the cpp example code to transfer a large number of messages, I find that I cannot use up the bandwidth. This causes a delay in the display. 

- Version: main branch
- Platform: Ubuntu20.04, mac os m1 pro, bandwidth 100Mbps.

**Steps To Reproduce**

**Expected Behavior**
The maximum bandwidth in my test environment was 100Mbps， When I run  frontend  and ws-cpp on same machine  The bandwidth is about 30Mbps, but when i run frontend  and ws-cpp on different machine, The bandwidth is about 10Mbps, This causes a delay in the display. But if I run two frontend on a machine, the bandwidth is about 20Mbps (10Mbps per tcp session). But single tcp connect should up to  30Mbps.
`So I don't think the front-end rendering is reaching a bottleneck, but is related to a single tcp connection.`

**Comment by wangqiim** [comment]
For the follow-up experiment, I used the network cable to make full use of the bandwidth. Bandwidth cannot be used when using the wireless network

**Comment by achim-k** [comment]
What bandwidth do you get if you run both the data source and Foxglove on the same host (locally)? This should give you an idea about how much your networking setup is responsible for a potential slowdown.

> For the follow-up experiment, I used the network cable to make full use of the bandwidth. Bandwidth cannot be used when using the wireless network

What was the outcome here?

**Comment by wangqiim** [comment]
> What bandwidth do you get if you run both the data source and Foxglove on the same host (locally)? This should give you an idea about how much your networking setup is responsible for a potential slowdown.
> 
> > For the follow-up experiment, I used the network cable to make full use of the bandwidth. Bandwidth cannot be used when using the wireless network
> 
> What was the outcome here?

The outcome is that the bandwidth of the network interface bandwidth has exceed the actual data transfer. (but the wireless network may not be as reliable as the wired connection, so a single TCP connection is extremely vulnerable.)

**Comment by wangqiim** [comment]
> So do I understand you right that you have solved your problem and this issue can be closed?

Yes
