### ISSUE TITLE
Missing implementation of setupTlsHandler (C++)

### ISSUE THREAD

**Issue by souryavarenya** [foxglove/ws-protocol#540]
**Description**

I find that the C++ implementation in this repo diverges from https://github.com/foxglove/ros-foxglove-bridge/tree/main/foxglove_bridge_base

The implementation of `setupTlsHandler()`  https://github.com/foxglove/ros-foxglove-bridge/blob/main/foxglove_bridge_base/src/server_factory.cpp is missing.

The examples get away by defining empty specialization inside the example source.
https://github.com/foxglove/ws-protocol/blob/04d8f95cb302d94cd0a2b0e48f96ddac89deeccc/cpp/examples/src/example_server_protobuf.cpp#L19-L22

Is this intentional? Is it the consumer's responsibility to define this?

Thanks in advance.

---

- Version: 
- Platform: C++ / Ubuntu 22.04

**Steps To Reproduce**

...

**Expected Behavior**

...

**Comment by achim-k** [comment]
Yeah, I'm aware that this is a nuisance. Will look for a solution to fix this

**Comment by achim-k** [comment]
> Is there anything speaking against borrowing this implementation? https://github.com/foxglove/ros-foxglove-bridge/blob/main/foxglove_bridge_base/src/server_factory.cpp

No, I did exactly that in #545. Does that work for you?

**Comment by souryavarenya** [comment]
Lovely! Looks good. 

Thanks :smiley:
