### ISSUE TITLE
Foxglove Studio not respecting spec for subscribe message

### ISSUE THREAD

**Issue by bertaveira** [foxglove/ws-protocol#719]
**Description**

I was implementing a Go version of this ws-socket protocol and noticed that the subIDs and ChanIDs were getting mixed up and subscriptions not working properly with my implementation. Further investigation revealed that foxglove studio was not sending the channelID in the subscribe message as described in the spec of this protocol. 

Here is a message from foxglove studio:
```
{\"op\":\"subscribe\",\"subscriptions\":[{\"id\":0}]}
```
As you can see it is missing the channelID.

My question is how can the websocket server know what channel this refers to? And am I missing something? Is this just an outdated documentation problem?

**Comment by bertaveira** [comment]
Ok it seems that I was forgetting to send the ID when I advertised the channel. Still somewhat weird that foxglove studio accepts this advertisement and even subscribes to the message with no channelID

**Comment by jtbandes** [comment]
Thanks for the report, the app will now display an error if these are missing.
