### ISSUE TITLE
C++ type definition doesn't contain schemaEncoding field

### ISSUE THREAD

**Issue by paulsohn** [foxglove/ws-protocol#875]
**Description**

https://github.com/foxglove/ws-protocol/blob/a28e0b9c9c319a1803bc00184d76fdb97714e921/cpp/foxglove-websocket/include/foxglove/websocket/common.hpp#L77-L83

Tried to use client publish capability, but currently C++ type definition doesn't contain schemaEncoding field.

- Version: main
- Platform:

**Steps To Reproduce**

N/A

**Expected Behavior**
should contain schemaEncoding in the definition, and adjust server behavior if needed

**Comment by paulsohn** [comment]
Sorry for misplaced ticket title.

**Comment by jtbandes** [comment]
Additionally it seems `schema` is never populated when received by the server... https://github.com/foxglove/ws-protocol/blob/a28e0b9c9c319a1803bc00184d76fdb97714e921/cpp/foxglove-websocket/include/foxglove/websocket/websocket_server.hpp#L1337-L1341

And is not included in the message sent from the client: https://github.com/foxglove/ws-protocol/blob/a28e0b9c9c319a1803bc00184d76fdb97714e921/cpp/foxglove-websocket/include/foxglove/websocket/websocket_client.hpp#L22-L25

**Comment by paulsohn** [comment]
@jtbandes 

If it's just unimplemented feature, then `schema` might take some breaking change as well like
```cpp
struct ClientAdvertisement {
  // ...omit
  std::string schemaName;
  std::optional<std::vector<uint8_t>> schema; // or even std::optional<std::string> schema;
  std::optional<std::string> schemaEncoding;
};
```
