### ISSUE TITLE
Library installation on windows 11

### ISSUE THREAD

**Issue by ZigiMigi** [foxglove/ws-protocol#90]
Hi,
I am having trouble installing your library ```foxglove-websocket```. Im on windows 11 and i used next commands:
-  pip install foxglove-websocket
- conda install foxglove-websocket
- also tried installing it via Pycharm package manager

All of the above commands give out the same error:
 ```PackagesNotFoundError: The following packages are not available from current channels: foxglove``` 

Is there something that I am doing wrong or is Windows 11 not supported yet?

**Comment by jtbandes** [comment]
I have Windows 11 running in a virtual machine and I was able to run `pip install foxglove-websocket` successfully followed by `python -m foxglove_websocket.examples.json_server`. Can you paste the full error output from pip?

**Comment by ZigiMigi** [comment]
@jtbandes 
yes of course. The full error is:
```with pip install foxglove-websocket``` 
ERROR: Could not find a version that satisfies the requirement foxglove-websocket (from versions: none)
ERROR: No matching distribution found for foxglove-websocket
```with Pycharm packet manager```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.


PackagesNotFoundError: The following packages are not available from current channels:

  - foxglove-websocket

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

ALSO:
- I am using Python 3.7

**Comment by jtbandes** [comment]
What is the output of `pip --version`? Can you try `python3 -m pip install foxglove-websocket`?

**Comment by ZigiMigi** [comment]
```py3 -m pip install foxglove-websocket``` worked for me.

Thanks for your help!!
